# Generated by Django 4.2.4 on 2023-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoConfigs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cryptos',
            fields=[
                ('id_crypto', models.AutoField(primary_key=True, serialize=False)),
                ('crypto', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
