# Generated by Django 4.2.4 on 2023-08-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoConfigs', '0002_cryptos_delete_quotation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cryptos',
            new_name='crypto',
        ),
    ]
