# Generated by Django 4.2.4 on 2023-08-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoConfigs', '0003_rename_cryptos_crypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='price',
            new_name='valor',
        ),
    ]
